from service import views
from django.urls import path

urlpatterns = [
    path('', views.index),
    path('news/', views.news),
    path('news/<str:id>', views.single_news),
    path('cat/<str:id>', views.cat_news),
    path('contact-us/', views.contact_us),
    path('about-us/', views.about_us),
    path('faq/', views.faq),
    path('subscribe/newsletter', views.insert_newsletter),
    path('problem/send', views.problem_send),
    path('problem/<int:id>', views.single_problem),
    path('ekrishi/<str:sldname>/', views.ekrishi),
    path('<str:pro_name>/', views.single_service),
    path('advice/<str:advice>/', views.fram_advice),
    path('quick/solve/', views.quick_solve),
    path('quick/<str:title>', views.single_quick_solve),
    path('farmer/reg/', views.farmer_reg),
    path('my/dashboard/', views.dashboard),
    path('farmer/login/', views.login),
    path('farmer/logout/', views.logout),
    path('my/profile', views.profile),
    path('edit-profile/<int:id>', views.edit_profile),
    path('change/my/password/', views.change_password),
    path('add/product', views.my_product),
    path('my/product/list/', views.my_product_list),
    path('buying/product/', views.product),
    path('<str:far_name>/<str:pro>/details/', views.single_product),
    path('product/add-to-cart/<int:id>/',views.add_to_cart),  
    path('product/delete-cart/<int:id>/',views.delete_to_cart), 
    path('order-my/product/', views.order_now), 
    path('admin/<int:id>/product-approve/', views.product_approve),
    path('admin/<int:id>/send-mail/', views.mail_custom),
    path('admin/<int:id>/approve/', views.agri_experience_approve),
    path('product/<int:id>/delivery/', views.product_delivery),
    path('seeling/request/', views.seeling_request),
    path('data/search/', views.data_search),
    path('agricultural/experience', views.agricultural_experience),
    path('experience/<str:id>', views.single_agricultural_experience),
    path('history/<str:id>', views.single_about),
]
