# Generated by Django 2.0.1 on 2020-04-28 05:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('ordering', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('comment', ckeditor.fields.RichTextField(blank=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='thumbnailimage/')),
                ('blog_image', models.ImageField(blank=True, upload_to='blog/')),
                ('blog_details', ckeditor.fields.RichTextField(blank=True)),
                ('blog_alt_tag', models.CharField(blank=True, max_length=200)),
                ('posted_By', models.CharField(blank=True, max_length=200)),
                ('ordering', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.BlogCategory')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(blank=True, max_length=100)),
                ('company_logo', models.ImageField(blank=True, upload_to='company_logo')),
                ('staring_year', models.IntegerField(default=2020)),
                ('email1', models.CharField(blank=True, max_length=100)),
                ('email2', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('mobile1', models.CharField(blank=True, max_length=15)),
                ('mobile2', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200)),
                ('pinterest', models.CharField(blank=True, max_length=200)),
                ('skype', models.CharField(blank=True, max_length=200)),
                ('youtube', models.CharField(blank=True, max_length=200)),
                ('Short Description', ckeditor.fields.RichTextField(blank=True)),
                ('com_story', ckeditor.fields.RichTextField(blank=True)),
                ('glg_map', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Info',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=150)),
                ('message', ckeditor.fields.RichTextField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='SubscriberNewslatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(max_length=254)),
                ('subscirbe_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News Letter',
                'verbose_name_plural': 'Subscriber News Letters',
            },
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Blogs'),
        ),
    ]
