# Generated by Django 2.0.3 on 2021-03-13 21:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_problemcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('title', models.TextField(max_length=200)),
                ('problem', ckeditor.fields.RichTextField()),
                ('problem_file', models.FileField(blank=True, upload_to='problem_file/')),
                ('ordering', models.IntegerField(default=0)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('solve_message', ckeditor.fields.RichTextField(blank=True)),
                ('slove', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ProblemCategory')),
            ],
            options={
                'verbose_name': 'Customer Problem',
                'verbose_name_plural': 'Customer Problems',
            },
        ),
    ]
