# Generated by Django 2.0.1 on 2020-05-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_alt_tag',
        ),
    ]
