# Generated by Django 2.0.3 on 2021-04-27 09:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_customerproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPesticides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('search_count', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Search Pesticides',
                'verbose_name_plural': 'Search Pesticides',
            },
        ),
        migrations.CreateModel(
            name='TreeAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tree Age',
                'verbose_name_plural': 'Tree Ages',
            },
        ),
        migrations.CreateModel(
            name='TreeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tree Name',
                'verbose_name_plural': 'Tree Names',
            },
        ),
        migrations.AddField(
            model_name='searchpesticides',
            name='tree_age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.TreeAge'),
        ),
        migrations.AddField(
            model_name='searchpesticides',
            name='tree_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.TreeName'),
        ),
    ]
