# Generated by Django 2.0.3 on 2021-04-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210427_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpesticides',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
