# Generated by Django 2.0.1 on 2020-05-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_blogs_blog_alt_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('images', models.ImageField(blank=True, upload_to='team_member/')),
                ('member_mobile', models.CharField(blank=True, max_length=15)),
                ('member_email', models.CharField(blank=True, max_length=60)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('twitter', models.CharField(blank=True, max_length=150)),
                ('linkedin', models.CharField(blank=True, max_length=150)),
                ('yahoo', models.CharField(blank=True, max_length=150)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('member_address', models.TextField(blank=True, max_length=200)),
                ('ordering', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Our Team Member',
                'verbose_name_plural': 'OurTeam Members',
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='story_video_link',
            field=models.TextField(blank=True),
        ),
    ]
