# Generated by Django 2.0.3 on 2021-04-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210427_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeage',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treename',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
