# Generated by Django 2.0.1 on 2020-05-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200511_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourteammember',
            options={'verbose_name': 'Our Team Member', 'verbose_name_plural': 'Our Team Members'},
        ),
        migrations.RemoveField(
            model_name='ourteammember',
            name='yahoo',
        ),
    ]
