# Generated by Django 2.0.1 on 2020-05-11 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200511_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteammember',
            name='member_designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
