# Generated by Django 2.0.1 on 2020-08-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_sliderinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderinfo',
            name='details',
        ),
    ]
