# Generated by Django 2.0.1 on 2020-08-23 10:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20200820_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderinfo',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
