# Generated by Django 2.0.1 on 2020-08-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20200823_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderinfo',
            name='slider_name',
        ),
    ]
