# Generated by Django 2.0.1 on 2020-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_sliderinfo_slider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderinfo',
            name='slider_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
