# Generated by Django 2.0.1 on 2020-08-23 18:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20200824_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproblem',
            name='solve',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
