# Generated by Django 2.0.1 on 2020-08-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_customerproblem_solve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproblem',
            name='file',
            field=models.FileField(blank=True, upload_to='file/'),
        ),
    ]
