# Generated by Django 2.0.1 on 2020-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20200824_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproblem',
            name='file',
        ),
        migrations.AddField(
            model_name='customerproblem',
            name='problem_file',
            field=models.FileField(blank=True, upload_to='problem_file/'),
        ),
    ]
