# Generated by Django 2.0.1 on 2020-08-24 08:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_auto_20200824_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('icon_img', models.ImageField(blank=True, upload_to='icon_img/')),
                ('ordering', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agricultural Advice',
                'verbose_name_plural': 'Agricultural Advices',
            },
        ),
    ]
