# Generated by Django 2.0.1 on 2020-08-24 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_agriculturaladvice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproblem',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
