# Generated by Django 2.0.1 on 2020-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_customerproblem_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproblem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
