# Generated by Django 2.0.1 on 2020-08-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_auto_20200824_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerproblem',
            old_name='status',
            new_name='slove',
        ),
        migrations.RenameField(
            model_name='customerproblem',
            old_name='solve',
            new_name='solve_message',
        ),
    ]
