# Generated by Django 2.0.3 on 2020-10-06 06:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_quicksolve'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('qt_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Add To Cart',
                'verbose_name_plural': 'Add To Cart',
            },
        ),
        migrations.CreateModel(
            name='CustomarAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=170, unique=True)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Customar Account',
                'verbose_name_plural': 'Customar Account',
            },
        ),
        migrations.CreateModel(
            name='CustomarOrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('b', 'Bkash'), ('d', 'Rocket'), ('o', 'Others')], max_length=1)),
                ('payment_number', models.CharField(max_length=150)),
                ('payment_txt_id', models.CharField(max_length=150)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Order List',
                'verbose_name_plural': 'Order Lists',
            },
        ),
        migrations.CreateModel(
            name='FarmerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=170, unique=True)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Farmer Account',
                'verbose_name_plural': 'Farmer Account',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_image', models.ImageField(upload_to='images/product_image')),
                ('product_price', models.IntegerField(default=0)),
                ('total_sale', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('status', models.BooleanField(default=0)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.FarmerAccount')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='customarorderlist',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Product'),
        ),
        migrations.AddField(
            model_name='customarorderlist',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.CustomarAccount'),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Product'),
        ),
    ]
