# Generated by Django 2.0.3 on 2020-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_auto_20201006_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmeraccount',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='farmeraccount',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
