# Generated by Django 2.0.3 on 2020-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_auto_20201006_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
