# Generated by Django 2.0.3 on 2020-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_auto_20201006_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product_image'),
        ),
    ]
