# Generated by Django 2.0.3 on 2020-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_auto_20201006_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=0),
        ),
    ]
