# Generated by Django 2.0.3 on 2020-10-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_product_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtocart',
            options={'verbose_name': 'Add To Cart', 'verbose_name_plural': 'Add To Carts'},
        ),
        migrations.AddField(
            model_name='product',
            name='total_sale',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customarorderlist',
            name='payment_type',
            field=models.CharField(choices=[('b', 'Bkash'), ('d', 'Rocket')], max_length=1),
        ),
    ]
