# Generated by Django 2.0.3 on 2020-10-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_auto_20201007_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customarorderlist',
            name='delivered_date',
        ),
        migrations.RemoveField(
            model_name='customarorderlist',
            name='user_name',
        ),
        migrations.AddField(
            model_name='customarorderlist',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.FarmerAccount'),
        ),
        migrations.AddField(
            model_name='product',
            name='approve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
