# Generated by Django 2.0.3 on 2020-10-07 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_auto_20201007_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customarorderlist',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
