# Generated by Django 2.0.3 on 2020-10-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_auto_20201007_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='news',
            field=models.TextField(blank=True),
        ),
    ]
