# Generated by Django 2.0.3 on 2020-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_auto_20201020_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(upload_to='product_image1/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, upload_to='product_image2/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, upload_to='product_image3/'),
        ),
    ]
