# Generated by Django 2.0.3 on 2020-10-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0039_auto_20201020_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Agricultural experience', 'verbose_name_plural': 'Agricultural experiences'},
        ),
    ]
