# Generated by Django 2.0.3 on 2020-10-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0040_auto_20201022_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('urls', models.TextField(blank=True)),
                ('ordering', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.DistrictCat')),
            ],
            options={
                'verbose_name': 'Important Link',
                'verbose_name_plural': 'Important Links',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
