# Generated by Django 2.0.3 on 2020-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0041_auto_20201022_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtcat',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_for',
            field=models.CharField(choices=[('1', 'KG'), ('2', 'Number')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
