# Generated by Django 2.0.3 on 2021-03-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0042_auto_20201022_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'News Category', 'verbose_name_plural': 'News Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
